kimtahen
hforif/forif-site pull request #9
Opened 2020-08-23 13:06 UTC by kimtahen

announcement의 보여주는 방식을 수정하였습니다.

2020-08-23 14:25 UTC, kimtahen commented
글꼴도 구글 폰트를 가져와서 수정하였습니다.

2020-08-23 16:30 UTC, YerinCho requested changes
실행은 안 해봐서 css는 못 봐주겠음...

2020-08-23 16:30 UTC, YerinCho commented on src/pages/Announcement.js
> +
announcement 라는 패키지를 만들고, 그 패키지 안에 Studies.js, TemplatesWrapper.js, PreviewTemplate.js, Template.js, pageQuery.js 로 파일을 나누면 좋을 것 같아요

2020-08-23 16:30 UTC, YerinCho commented on src/pages/Announcement.js
> +      else onClickResetEvent()
함수로 빼주면 안 돼요 ㅜ?
그리고 !isVisible 처럼 부정형으로 처리하는것보다
```suggestion
      if (isVisible) {
        onClickResetEvent()
        return;
      }
      onClickEvent()
```
로 처리하는 게 가독성이 높아요!
else 안쓴건 제가 원래 else 쓰는걸 안좋아해요

2020-08-23 16:30 UTC, YerinCho commented on src/pages/Announcement.js
> +  const [isVisible, setIsVisible] = useState(0)
변수이름을 보면 0, 1로 표현하기보다는 boolean 형으로 표현하는게 맞지 않을까요?
초기값은 false로 해주면 될 것 같아요.

2020-08-23 16:30 UTC, YerinCho commented on src/pages/Announcement.js
> +      {(isVisible === 1) && <Template
isVisible이 boolean이 된다면
```suggestion
      {isVisible && <Template
```
도 될 것 같아요!

2020-08-23 16:30 UTC, YerinCho commented on src/pages/Announcement.js
> +        func(0)
```suggestion
        func(true)
      } else {
        func(false)
```

2020-08-23 16:30 UTC, YerinCho commented on src/pages/Announcement.js
> +        })}
```suggestion
        {edges.map((value, index) => (
            <TemplatesWrapper
            value={value} 
            index={index} 
            key={index}
            setIsVisibleList={setIsVisibleList}
            setOnClickListener={setOnClickListener}/>
        ))}
```

2020-08-24 00:28 UTC, kimtahen commented on src/pages/Announcement.js
> +
쿼리는 같은파일에 써야 자동으로 처리가 되는거같아서 그렇구,, 코드가 그리길지않아서 한파일에썼습니다ㅏ..

2020-08-24 00:29 UTC, kimtahen commented on src/pages/Announcement.js
> +  const [isVisible, setIsVisible] = useState(0)
0 1 외에 -1이 필요해서 정수로 사용하였습니다.

2020-08-24 00:29 UTC, kimtahen commented on src/pages/Announcement.js
> +      else onClickResetEvent()
앗 그렇군요 ㅋㅋ

2020-08-24 05:24 UTC, YerinCho commented on src/pages/Announcement.js
> +
오, 길진 않아도 추후 코드가 길어질 수도 있고, 유지보수의 측면에서 보통 다른 파일로 분리해요 :)

2020-08-24 05:26 UTC, YerinCho commented on src/pages/Announcement.js
> +  const [isVisible, setIsVisible] = useState(0)
궁금한데, onClickListener에서 -1 쓰이는 경우 말고 언제 -1 쓰여요?

2020-08-25 14:16 UTC, kimtahen commented on src/pages/Announcement.js
> +  const onClickEvent = () => setOnClickListener(index)
@YerinCho 여기에서 쓰여요

2020-08-26 09:54 UTC, merged